setwd("../fastvla_data")
library(FastReg)
#aa = FastVLA::generate.dataset(seed = 123, num.pc = 20, num.subj = 500, num.variants = 5000, num.pheno = 5)
testt = BEDMatrix::BEDMatrix("plink/testdata_5k_by_50k.bed")

Y = readRDS("Y_log.rds")
X = readRDS("X.rds")
a = proc.time()
FastVLA_logistic(Y, slot(testt, "xptr"), 1:500, 1:500, X, 100, "test", colnames(Y), paste0("Y", 1:500), "VB_MR2", epss = 1e-16, mafthresh = 0.08)
show(proc.time() - a)