---
title: "FastReg"
author: "Matt Wheeler, Deepak Mav, John House, Shail Choksi, Adam Burkholder"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{FastReg}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Pre-requisites

-   BLAS/MKL libraries installed. We recommend using Intel MKL (https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl-download.html)
-   HDF5 library - https://www.hdfgroup.org/downloads/hdf5/
-   Rtools for Windows

## Configuration file

Create a configuration file. All available configuration options are listed below:

-   **pheno.file** - relative path to phenotype file. Contains outcomes that will be modelled.

-   **phenotype** - column name to be modelled from the phenotype file

-   **pheno.file.delim** - delimiter used in phenotype file - tab\|space\|comma

-   **pheno.rownames.cols** - column to be treated as the subject identifier when matching across files. Can be multiple columns.

-   **subject.subset.rowname.cols** - column to be treated as the subject identifier when matching across files

-   **subject.subset.file (optional)** - relative path to subset subject file

-   **subject.subset.delim** - delimiter used in subject subset file - tab\|space\|comma

-   **covar.file** - relative path to covariates file

-   **covar.rowname.cols** - column to be treated as the subject identifier when matching across files

-   **covar.file.delim** - delimiter used in covariates file - tab\|space\|comma

-   **POI.file** - relative path to POI file

-   **POI.subset.file (optional)** - relative path to subset POI file

-   **POI.subset.file.delim** - delimiter used in POI subset file - tab\|space\|comma

-   **POI.file.delim** - delimiter used in POI file - tab\|space\|comma

-   **POI.file.format** - file format - text\|h5

-   **POI.subset.rowname.col** - column to be treated as the subject identifier when matching across files

-   **regression.type** - logistic\|linear

-   **covariates (optional)** column names of the covariates file - comma separated

-   **covariate.type (optional)** - column data type for covariates file - comma separated (numeric\|categorical)

-   **covariate.standardize (optional)** - which covariate to be standardized (1\|0 - comma separated)

-   **covariate.levels (optional)** - how many unique values for categorical columns. (; separated for covariate, comma separated for each unique value)

-   **covariate.ref.level (optional)** - First alphabetically sorted value (comma separated)

-   **output.dir** - relative path to directory for output. Directory will be created if it doesn't exist

-   **output.file.format** - long\|tall

-   **output.exclude.covar** - 0\|1

-   **hwe.threshold** - 0.00-1.00 \| default 1e-14

-   **maf.threshold** - 0.00-1.00

-   **POI.type** - genotypes\|numerical (dosage value data type)

-   **POI.effect.type** - additive\|dominant\|recessive

-   **no.intercept** - 0\|1 - to include the intercept term or not in the model

-   **colinearity.rsq** - r-squared threshold value to be used during the iterative addition of covariates (default - 0.99)

-   **poi.block.size (optional)** - block size. This is dynamically calculated by the package if its not provided

-   **max.iter** - max iterations. Default - 6

-   **max.cores (optional)** - max cores to use

-   **compress.results (optional)** - 0\|1, Default - 1

-   **verbose** - 0\|1, for debugging

### Example Configuration File

    pheno.file  example.bin.pheno.txt
    covar.file  example.covar.txt
    POI.file    example.poi.h5
    phenotype   bin.resp
    regression.type logistic
    pheno.rowname.cols  ind
    covar.rowname.cols  ind
    pheno.file.delim    tab
    covar.file.delim    tab
    subject.subset.delim    tab
    POI.subset.file.delim   tab
    POI.file.format h5
    POI.file.delim  tab
    subject.subset.rowname.cols ind
    POI.subset.rowname.col  rsID
    covariates  age,sex,eth,treatment,severity
    covariate.type  numeric,categorical,categorical,categorical,categorical
    covariate.standardize   1,0,0,0,0
    covariate.levels    ;F,M;afr,asi,eur;Placebo,Test;Very Low,Low,Moderate,High,Very High,Extreme
    covariate.ref.level ,F,eur,Placebo,Very Low
    output.dir  example.bin.output
    output.file.format  long
    output.exclude.covar    0
    hwe.threshold   0.05
    maf.threshold   0.01
    POI.type    genotypes
    POI.effect.type additive
    no.intercept  0
    colinearity.rsq 0.95
    poi.block.size  50000
    max.iter    6
    compress.results    1
    verbose 1

## Installation

Change the path below to where you have downloaded the tar.gz package.

install.packages(\"../../FastReg_0.4.2.tar.gz\", repos = NULL, type = \"source\");

library(\"FastReg\");

Create the configuration file and call the FastReg function with the path to the configuration file.

FastReg(config.file=\"vignette.example.config\")

