---
title: "FastReg: Efficient Logistic Regression"
author: "Matt Wheeler, Deepak Mav, John House, Shail Choksi, Adam Burkholder"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{FastReg: Efficient Logistic Regression}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Logistic Regression

```r
library(FastReg)
prefix <- "testdata_500_by_1k"
# disucss further complex examples with John. Talk with Betsy about complex Exwas models
FastReg::FastReg(
    phenotype="bin.resp", 
    max.iter = 6, 
    covariates = c("age","sex","treatment"),
    covariate.levels = ";F,M;Placebo,Test", # vectors / list of vectors 
    covariate.ref.level = ",F,Placebo", 
    covariate.type = "numeric,categorical,categorical",
    covariate.standardize = "1,0,0",
    covar.file= data(paste0(prefix, ".covar.txt"), package=FastReg),
    poi.file = data(paste0(prefix, ".poi.txt"), package=FastReg),
    pheno.file= data(paste0(prefix, ".bin.pheno.txt"), package=FastReg),
    regression.type="logistic",
    output.dir = "."
)
summary_file <- "POI_Summary.tsv"
summary_df <- read.table(summary_file, n=6, header=TRUE, sep="\t", check.names = FALSE, stringsAsFactors = FALSE)
print(summary_df)

results_file <- "Results_stratum.tsv"
results_df <- read.table(summary_file, n=6, header=TRUE, sep="\t", check.names = FALSE, stringsAsFactors = FALSE)
print(results_df)
```

The equivalent logistic regression formula for GLM would be:
bin.resp ~ 1 + Age + Sex + Treatment + Geno
Where Geno is the column added to the covariates. This assumes an additive model. 

### Limiting number of processes
FastReg automatically optimizes for the number of processes to spawn. It decides on the number of processes to use using the following formula:
minimum(number of POI files, number of available processes - 1)

If this is not the desired behavior, FastReg allows setting the number of processes using the max.workers parameter.
For example, to only spawn 2 worker processes:

```r
FastReg::FastReg(
    phenotype="bin.resp", 
    max.iter = 6, 
    covariates = c("age","sex","treatment"),
    covariate.levels = ";F,M;Placebo,Test", # vectors / list of vectors 
    covariate.ref.level = ",F,Placebo", 
    covariate.type = "numeric,categorical,categorical",
    covariate.standardize = "1,0,0",
    covar.file= data(paste0(prefix, ".covar.txt"), package=FastReg),
    poi.file = data(paste0(prefix, ".poi.txt"), package=FastReg),
    pheno.file= data(paste0(prefix, ".bin.pheno.txt"), package=FastReg),
    regression.type="logistic",
    output.dir = ".",
    max.workers = 2
)
```

### Optimizing for OpenMP
FastReg makes use of OpenMP to optimize repeated matrix operations. By default, it will try to use 2 OpenMP threads per worker process (except for MacOS - which only support single threaded OpenMP). 
To change the default, the max.openmp.threads parameter can be used.

For example, to use 3 OpenMP threads per worker process:\

```r
FastReg::FastReg(
    phenotype="bin.resp", 
    max.iter = 6, 
    covariates = c("age","sex","treatment"),
    covariate.levels = ";F,M;Placebo,Test", # vectors / list of vectors 
    covariate.ref.level = ",F,Placebo", 
    covariate.type = "numeric,categorical,categorical",
    covariate.standardize = "1,0,0",
    covar.file= data(paste0(prefix, ".covar.txt"), package=FastReg),
    poi.file = data(paste0(prefix, ".poi.txt"), package=FastReg),
    pheno.file= data(paste0(prefix, ".bin.pheno.txt"), package=FastReg),
    regression.type="logistic",
    output.dir = ".",
    max.workers = 2,
    max.openmp.threads = 3
)
```
This will spawn 2 worker processes and each process will use 3 OpenMP threads to perform repeated matrix operations.

