// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// standardize_and_derank_print
arma::mat standardize_and_derank_print(arma::mat x, const std::string& dir, const std::string& namee, const std::string& suffix, double dev_to_acc, double N);
RcppExport SEXP _FastVLA_standardize_and_derank_print(SEXP xSEXP, SEXP dirSEXP, SEXP nameeSEXP, SEXP suffixSEXP, SEXP dev_to_accSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dir(dirSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type namee(nameeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type suffix(suffixSEXP);
    Rcpp::traits::input_parameter< double >::type dev_to_acc(dev_to_accSEXP);
    Rcpp::traits::input_parameter< double >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(standardize_and_derank_print(x, dir, namee, suffix, dev_to_acc, N));
    return rcpp_result_gen;
END_RCPP
}
// FastVLA_logisticf
void FastVLA_logisticf(const arma::mat& Y, SEXP Gptr, const arma::ivec& v_index, const arma::ivec& i_index, const arma::mat& X, const int& chunk_size, const std::string& dir, const std::vector<std::string> cnames, const std::vector<std::string> vnames, const std::string suffix, const double epss, const double& mafthresh, const double& pca_var_explained, const int max_iter, const int max_threads, const int max_blas_threads, const bool do_pca, const bool add_intercept);
RcppExport SEXP _FastVLA_FastVLA_logisticf(SEXP YSEXP, SEXP GptrSEXP, SEXP v_indexSEXP, SEXP i_indexSEXP, SEXP XSEXP, SEXP chunk_sizeSEXP, SEXP dirSEXP, SEXP cnamesSEXP, SEXP vnamesSEXP, SEXP suffixSEXP, SEXP epssSEXP, SEXP mafthreshSEXP, SEXP pca_var_explainedSEXP, SEXP max_iterSEXP, SEXP max_threadsSEXP, SEXP max_blas_threadsSEXP, SEXP do_pcaSEXP, SEXP add_interceptSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Gptr(GptrSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type v_index(v_indexSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type i_index(i_indexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const int& >::type chunk_size(chunk_sizeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dir(dirSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string> >::type cnames(cnamesSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string> >::type vnames(vnamesSEXP);
    Rcpp::traits::input_parameter< const std::string >::type suffix(suffixSEXP);
    Rcpp::traits::input_parameter< const double >::type epss(epssSEXP);
    Rcpp::traits::input_parameter< const double& >::type mafthresh(mafthreshSEXP);
    Rcpp::traits::input_parameter< const double& >::type pca_var_explained(pca_var_explainedSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const int >::type max_threads(max_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type max_blas_threads(max_blas_threadsSEXP);
    Rcpp::traits::input_parameter< const bool >::type do_pca(do_pcaSEXP);
    Rcpp::traits::input_parameter< const bool >::type add_intercept(add_interceptSEXP);
    FastVLA_logisticf(Y, Gptr, v_index, i_index, X, chunk_size, dir, cnames, vnames, suffix, epss, mafthresh, pca_var_explained, max_iter, max_threads, max_blas_threads, do_pca, add_intercept);
    return R_NilValue;
END_RCPP
}
// FastVLA_logistic
void FastVLA_logistic(const arma::mat& Y, SEXP Gptr, const arma::ivec& v_index, const arma::ivec& i_index, const arma::mat& X, const int& chunk_size, const std::string& dir, const std::vector<std::string> cnames, const std::vector<std::string> vnames, const std::string suffix, const double epss, const double& mafthresh, const double& pca_var_explained, const int max_iter, const int max_threads, const int max_blas_threads, const bool do_pca, const bool add_intercept);
RcppExport SEXP _FastVLA_FastVLA_logistic(SEXP YSEXP, SEXP GptrSEXP, SEXP v_indexSEXP, SEXP i_indexSEXP, SEXP XSEXP, SEXP chunk_sizeSEXP, SEXP dirSEXP, SEXP cnamesSEXP, SEXP vnamesSEXP, SEXP suffixSEXP, SEXP epssSEXP, SEXP mafthreshSEXP, SEXP pca_var_explainedSEXP, SEXP max_iterSEXP, SEXP max_threadsSEXP, SEXP max_blas_threadsSEXP, SEXP do_pcaSEXP, SEXP add_interceptSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Gptr(GptrSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type v_index(v_indexSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type i_index(i_indexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const int& >::type chunk_size(chunk_sizeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dir(dirSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string> >::type cnames(cnamesSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string> >::type vnames(vnamesSEXP);
    Rcpp::traits::input_parameter< const std::string >::type suffix(suffixSEXP);
    Rcpp::traits::input_parameter< const double >::type epss(epssSEXP);
    Rcpp::traits::input_parameter< const double& >::type mafthresh(mafthreshSEXP);
    Rcpp::traits::input_parameter< const double& >::type pca_var_explained(pca_var_explainedSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const int >::type max_threads(max_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type max_blas_threads(max_blas_threadsSEXP);
    Rcpp::traits::input_parameter< const bool >::type do_pca(do_pcaSEXP);
    Rcpp::traits::input_parameter< const bool >::type add_intercept(add_interceptSEXP);
    FastVLA_logistic(Y, Gptr, v_index, i_index, X, chunk_size, dir, cnames, vnames, suffix, epss, mafthresh, pca_var_explained, max_iter, max_threads, max_blas_threads, do_pca, add_intercept);
    return R_NilValue;
END_RCPP
}
// FastVLA_chunked_sota
int FastVLA_chunked_sota(const arma::mat& Y, SEXP Gptr, const arma::ivec& v_index, const arma::ivec& i_index, const arma::mat& X, const int& chunk_size, const std::string& dir, const std::vector<std::string> cnames, const std::vector<std::string> vnames, const std::string suffix, const double epss, const double& mafthresh, const double pca_var_explained, const int max_threads, const int max_blas_threads);
RcppExport SEXP _FastVLA_FastVLA_chunked_sota(SEXP YSEXP, SEXP GptrSEXP, SEXP v_indexSEXP, SEXP i_indexSEXP, SEXP XSEXP, SEXP chunk_sizeSEXP, SEXP dirSEXP, SEXP cnamesSEXP, SEXP vnamesSEXP, SEXP suffixSEXP, SEXP epssSEXP, SEXP mafthreshSEXP, SEXP pca_var_explainedSEXP, SEXP max_threadsSEXP, SEXP max_blas_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Gptr(GptrSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type v_index(v_indexSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type i_index(i_indexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const int& >::type chunk_size(chunk_sizeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dir(dirSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string> >::type cnames(cnamesSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string> >::type vnames(vnamesSEXP);
    Rcpp::traits::input_parameter< const std::string >::type suffix(suffixSEXP);
    Rcpp::traits::input_parameter< const double >::type epss(epssSEXP);
    Rcpp::traits::input_parameter< const double& >::type mafthresh(mafthreshSEXP);
    Rcpp::traits::input_parameter< const double >::type pca_var_explained(pca_var_explainedSEXP);
    Rcpp::traits::input_parameter< const int >::type max_threads(max_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type max_blas_threads(max_blas_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(FastVLA_chunked_sota(Y, Gptr, v_index, i_index, X, chunk_size, dir, cnames, vnames, suffix, epss, mafthresh, pca_var_explained, max_threads, max_blas_threads));
    return rcpp_result_gen;
END_RCPP
}
// FastVLA_single_Y
int FastVLA_single_Y(const arma::vec& Y, SEXP Gptr, const arma::ivec& v_index, const arma::ivec& i_index, const arma::mat& X, const int& chunk_size, const std::string& dir, const std::vector<std::string> cnames, const std::vector<std::string> vnames, const std::string suffix, const double epss, const double& mafthresh, const double pca_var_explained, const bool do_pca, const bool add_intercept);
RcppExport SEXP _FastVLA_FastVLA_single_Y(SEXP YSEXP, SEXP GptrSEXP, SEXP v_indexSEXP, SEXP i_indexSEXP, SEXP XSEXP, SEXP chunk_sizeSEXP, SEXP dirSEXP, SEXP cnamesSEXP, SEXP vnamesSEXP, SEXP suffixSEXP, SEXP epssSEXP, SEXP mafthreshSEXP, SEXP pca_var_explainedSEXP, SEXP do_pcaSEXP, SEXP add_interceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Gptr(GptrSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type v_index(v_indexSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type i_index(i_indexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const int& >::type chunk_size(chunk_sizeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dir(dirSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string> >::type cnames(cnamesSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string> >::type vnames(vnamesSEXP);
    Rcpp::traits::input_parameter< const std::string >::type suffix(suffixSEXP);
    Rcpp::traits::input_parameter< const double >::type epss(epssSEXP);
    Rcpp::traits::input_parameter< const double& >::type mafthresh(mafthreshSEXP);
    Rcpp::traits::input_parameter< const double >::type pca_var_explained(pca_var_explainedSEXP);
    Rcpp::traits::input_parameter< const bool >::type do_pca(do_pcaSEXP);
    Rcpp::traits::input_parameter< const bool >::type add_intercept(add_interceptSEXP);
    rcpp_result_gen = Rcpp::wrap(FastVLA_single_Y(Y, Gptr, v_index, i_index, X, chunk_size, dir, cnames, vnames, suffix, epss, mafthresh, pca_var_explained, do_pca, add_intercept));
    return rcpp_result_gen;
END_RCPP
}
// FastVLA_single_Y_fast
int FastVLA_single_Y_fast(const arma::vec& Y, SEXP Gptr, const arma::ivec& v_index, const arma::ivec& i_index, const arma::mat& X, const int& chunk_size, const std::string& dir, const std::vector<std::string> cnames, const std::vector<std::string> vnames, const std::string suffix, const double epss, const double& mafthresh, const double pca_var_explained, const bool do_pca, const bool add_intercept);
RcppExport SEXP _FastVLA_FastVLA_single_Y_fast(SEXP YSEXP, SEXP GptrSEXP, SEXP v_indexSEXP, SEXP i_indexSEXP, SEXP XSEXP, SEXP chunk_sizeSEXP, SEXP dirSEXP, SEXP cnamesSEXP, SEXP vnamesSEXP, SEXP suffixSEXP, SEXP epssSEXP, SEXP mafthreshSEXP, SEXP pca_var_explainedSEXP, SEXP do_pcaSEXP, SEXP add_interceptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Gptr(GptrSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type v_index(v_indexSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type i_index(i_indexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const int& >::type chunk_size(chunk_sizeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dir(dirSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string> >::type cnames(cnamesSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string> >::type vnames(vnamesSEXP);
    Rcpp::traits::input_parameter< const std::string >::type suffix(suffixSEXP);
    Rcpp::traits::input_parameter< const double >::type epss(epssSEXP);
    Rcpp::traits::input_parameter< const double& >::type mafthresh(mafthreshSEXP);
    Rcpp::traits::input_parameter< const double >::type pca_var_explained(pca_var_explainedSEXP);
    Rcpp::traits::input_parameter< const bool >::type do_pca(do_pcaSEXP);
    Rcpp::traits::input_parameter< const bool >::type add_intercept(add_interceptSEXP);
    rcpp_result_gen = Rcpp::wrap(FastVLA_single_Y_fast(Y, Gptr, v_index, i_index, X, chunk_size, dir, cnames, vnames, suffix, epss, mafthresh, pca_var_explained, do_pca, add_intercept));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FastVLA_standardize_and_derank_print", (DL_FUNC) &_FastVLA_standardize_and_derank_print, 6},
    {"_FastVLA_FastVLA_logisticf", (DL_FUNC) &_FastVLA_FastVLA_logisticf, 18},
    {"_FastVLA_FastVLA_logistic", (DL_FUNC) &_FastVLA_FastVLA_logistic, 18},
    {"_FastVLA_FastVLA_chunked_sota", (DL_FUNC) &_FastVLA_FastVLA_chunked_sota, 15},
    {"_FastVLA_FastVLA_single_Y", (DL_FUNC) &_FastVLA_FastVLA_single_Y, 15},
    {"_FastVLA_FastVLA_single_Y_fast", (DL_FUNC) &_FastVLA_FastVLA_single_Y_fast, 15},
    {NULL, NULL, 0}
};

RcppExport void R_init_FastVLA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
