# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' This function is the exported wrapper that can be called from R. It has the
NULL

FastVLA_logisticf <- function(Y, Gptr, v_index, i_index, X, chunk_size, dir, cnames, vnames, suffix, epss = 1e-6, mafthresh = 0.005, pca_var_explained = 0.95) {
    invisible(.Call(`_FastVLA_FastVLA_logisticf`, Y, Gptr, v_index, i_index, X, chunk_size, dir, cnames, vnames, suffix, epss, mafthresh, pca_var_explained))
}

FastVLA_logistic <- function(Y, Gptr, v_index, i_index, X, chunk_size, dir, cnames, vnames, suffix, epss = 1e-6, mafthresh = 0.005, pca_var_explained = 0.95) {
    invisible(.Call(`_FastVLA_FastVLA_logistic`, Y, Gptr, v_index, i_index, X, chunk_size, dir, cnames, vnames, suffix, epss, mafthresh, pca_var_explained))
}

FastVLA_chunked_sota <- function(Y, Gptr, v_index, i_index, X, chunk_size, dir, cnames, vnames, suffix, epss = 1e-6, mafthresh = 0.005, pca_var_explained = 0.95) {
    .Call(`_FastVLA_FastVLA_chunked_sota`, Y, Gptr, v_index, i_index, X, chunk_size, dir, cnames, vnames, suffix, epss, mafthresh, pca_var_explained)
}

